// codereact/banking-system/src/presentation/views/ClientList.tsx
import React, { useState, useEffect } from 'react';
import { Client } from '../../domain/entities/Client';
import { ClientController } from '../../application/controllers/ClientController';
import { ClientApiRepository } from '../../infrastructure/api/ClientApiRepository';
import '../styles/Views.css';
import '../styles/Table.css';

interface ClientFormProps {
  client: Client | null;
  onSubmit: (client: Client) => void;
  onCancel: () => void;
}

const ClientForm: React.FC<ClientFormProps> = ({ client, onSubmit, onCancel }) => {
  const [formData, setFormData] = useState<Client>({
    fullName: client?.fullName || '',
    address: client?.address || '',
    phone: client?.phone || '',
    password: client?.password || '',
    status: client?.status ?? true
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit}>
      <div className="form-group">
        <label>Nombre completo:</label>
        <input
          type="text"
          className="form-control"
          value={formData.fullName}
          onChange={(e) => setFormData({ ...formData, fullName: e.target.value })}
          required
        />
      </div>
      <div className="form-group">
        <label>Dirección:</label>
        <input
          type="text"
          className="form-control"
          value={formData.address}
          onChange={(e) => setFormData({ ...formData, address: e.target.value })}
          required
        />
      </div>
      <div className="form-group">
        <label>Teléfono:</label>
        <input
          type="text"
          className="form-control"
          value={formData.phone}
          onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
          required
        />
      </div>
      <div className="form-group">
        <label>Contraseña:</label>
        <input
          type="password"
          className="form-control"
          value={formData.password}
          onChange={(e) => setFormData({ ...formData, password: e.target.value })}
          required
        />
      </div>
      <div className="form-actions">
        <button type="submit" className="btn btn-primary">
          {client ? 'Actualizar' : 'Crear'}
        </button>
        <button type="button" className="btn btn-secondary" onClick={onCancel}>
          Cancelar
        </button>
      </div>
    </form>
  );
};

const ClientList = () => {
  const [clients, setClients] = useState<Client[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedClient, setSelectedClient] = useState<Client | null>(null);
  const controller = new ClientController(new ClientApiRepository());

  useEffect(() => {
    loadClients();
  }, []);

  const loadClients = async () => {
    try {
      setLoading(true);
      const data = await controller.getAllClients();
      setClients(data);
      setError(null);
    } catch (error) {
      setError('Error al cargar los clientes. Por favor, intente nuevamente.');
      console.error('Error loading clients:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = async (client: Client) => {
    try {
      await controller.createClient(client);
      await loadClients();
      setIsModalOpen(false);
    } catch (error) {
      setError('Error al crear el cliente. Por favor, intente nuevamente.');
      console.error('Error creating client:', error);
    }
  };

  const handleUpdate = async (id: number, client: Client) => {
    try {
      await controller.updateClient(id, client);
      await loadClients();
      setIsModalOpen(false);
    } catch (error) {
      setError('Error al actualizar el cliente. Por favor, intente nuevamente.');
      console.error('Error updating client:', error);
    }
  };

  const handleDelete = async (id: number) => {
    if (window.confirm('¿Está seguro que desea eliminar este cliente?')) {
      try {
        await controller.deleteClient(id);
        await loadClients();
        setError(null);
      } catch (error) {
        setError('Error al eliminar el cliente. Por favor, intente nuevamente.');
        console.error('Error deleting client:', error);
      }
    }
  };

  const handleStatusChange = async (id: number, currentStatus: boolean) => {
    try {
      if (currentStatus) {
        await controller.deactivateClient(id);
      } else {
        await controller.activateClient(id);
      }
      await loadClients();
      setError(null);
    } catch (error) {
      setError('Error al actualizar el estado del cliente. Por favor, intente nuevamente.');
      console.error('Error updating client status:', error);
    }
  };

  if (loading) {
    return <div className="loading">Cargando...</div>;
  }

  if (error) {
    return <div className="error">{error}</div>;
  }

  return (
    <div className="view-container">
      <div className="view-header">
        <h1>Lista de Clientes</h1>
        <button 
          className="btn btn-primary"
          onClick={() => {
            setSelectedClient(null);
            setIsModalOpen(true);
          }}
        >
          Nuevo Cliente
        </button>
      </div>

      <div className="table-container">
        <table className="data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Nombre</th>
              <th>Dirección</th>
              <th>Teléfono</th>
              <th>Estado</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            {clients.map((client) => (
              <tr key={client.id}>
                <td>{client.id}</td>
                <td>{client.fullName}</td>
                <td>{client.address}</td>
                <td>{client.phone}</td>
                <td>
                  <span className={`status ${client.status ? 'active' : 'inactive'}`}>
                    {client.status ? 'Activo' : 'Inactivo'}
                  </span>
                </td>
                <td>
                  <button
                    onClick={() => {
                      setSelectedClient(client);
                      setIsModalOpen(true);
                    }}
                    className="btn btn-secondary"
                  >
                    Editar
                  </button>
                  <button
                    onClick={() => handleStatusChange(client.id!, client.status)}
                    className={`btn ${client.status ? 'btn-warning' : 'btn-success'}`}
                  >
                    {client.status ? 'Desactivar' : 'Activar'}
                  </button>
                  <button
                    onClick={() => handleDelete(client.id!)}
                    className="btn btn-danger"
                  >
                    Eliminar
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {isModalOpen && (
        <div className="modal">
          <div className="modal-content">
            <h2>{selectedClient ? 'Editar Cliente' : 'Nuevo Cliente'}</h2>
            <ClientForm
              client={selectedClient}
              onSubmit={(client) => {
                if (selectedClient) {
                  handleUpdate(selectedClient.id!, client);
                } else {
                  handleCreate(client);
                }
              }}
              onCancel={() => setIsModalOpen(false)}
            />
          </div>
        </div>
      )}
    </div>
  );
};

export default ClientList;

// frontend/banking-system/src/app/presentation/modules/client/components/client-list/client-list.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { Subject, takeUntil } from 'rxjs';
import { ClientUseCases } from '@application/use-cases/client.use-cases';
import { Client } from '@domain/entities/client.entity';

/**
 * Client List Component following MVC pattern
 * Controller for managing client list view and operations
 */
@Component({
  selector: 'app-client-list',
  templateUrl: './client-list.component.html',
  styleUrls: ['./client-list.component.css']
})
export class ClientListComponent implements OnInit, OnDestroy {
  clients: Client[] = [];
  filteredClients: Client[] = [];
  loading = false;
  error: string | null = null;
  searchTerm = '';

  private destroy$ = new Subject<void>();

  constructor(
    private readonly clientUseCases: ClientUseCases,
    private readonly router: Router
  ) {}

  ngOnInit(): void {
    this.loadClients();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  /**
   * Load all clients from the system
   */
  loadClients(): void {
    this.loading = true;
    this.error = null;

    this.clientUseCases.getAllClients()
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (clients) => {
          this.clients = clients;
          this.filteredClients = clients;
          this.loading = false;
        },
        error: (error) => {
          this.error = 'Error al cargar los clientes: ' + error.message;
          this.loading = false;
        }
      });
  }

  /**
   * Filter clients based on search term
   */
  onSearch(): void {
    if (!this.searchTerm.trim()) {
      this.filteredClients = this.clients;
      return;
    }

    const term = this.searchTerm.toLowerCase();
    this.filteredClients = this.clients.filter(client =>
      client.person.fullName.toLowerCase().includes(term) ||
      client.person.phone.toLowerCase().includes(term) ||
      client.person.address.toLowerCase().includes(term)
    );
  }

  /**
   * Navigate to create new client form
   */
  createClient(): void {
    this.router.navigate(['/clientes/nuevo']);
  }

  /**
   * Navigate to edit client form
   */
  editClient(clientId: number): void {
    this.router.navigate(['/clientes/editar', clientId]);
  }

  /**
   * Activate client account
   */
  activateClient(clientId: number): void {
    if (!confirm('¿Está seguro de que desea activar este cliente?')) {
      return;
    }

    this.clientUseCases.activateClient(clientId)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: () => {
          this.loadClients();
        },
        error: (error) => {
          this.error = 'Error al activar el cliente: ' + error.message;
        }
      });
  }

  /**
   * Deactivate client account
   */
  deactivateClient(clientId: number): void {
    if (!confirm('¿Está seguro de que desea desactivar este cliente?')) {
      return;
    }

    this.clientUseCases.deactivateClient(clientId)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: () => {
          this.loadClients();
        },
        error: (error) => {
          this.error = 'Error al desactivar el cliente: ' + error.message;
        }
      });
  }

  /**
   * Delete client from the system
   */
  deleteClient(clientId: number): void {
    if (!confirm('¿Está seguro de que desea eliminar este cliente? Esta acción no se puede deshacer.')) {
      return;
    }

    this.clientUseCases.deleteClient(clientId)
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: () => {
          this.loadClients();
        },
        error: (error) => {
          this.error = 'Error al eliminar el cliente: ' + error.message;
        }
      });
  }

  /**
   * Get status badge class for client
   */
  getStatusClass(status: boolean): string {
    return status ? 'status-active' : 'status-inactive';
  }

  /**
   * Get status text for client
   */
  getStatusText(status: boolean): string {
    return status ? 'Activo' : 'Inactivo';
  }

  /**
   * Track by function for ngFor optimization
   */
  trackByClientId(index: number, client: Client): number {
    return client.id || index;
  }
}
<div class="content-header">
  <h1 class="page-title">Clientes</h1>
</div>

<div class="action-bar">
  <div class="search-container">
    <input 
      type="text" 
      class="search-input" 
      placeholder="Buscar"
      [(ngModel)]="searchTerm"
      (input)="onSearch()">
  </div>
  <button class="btn btn-primary" (click)="createClient()">
    Nuevo
  </button>
</div>

<div *ngIf="loading" class="text-center">
  <div class="loading-spinner"></div>
  Cargando clientes...
</div>

<div *ngIf="error" class="alert alert-danger">
  {{ error }}
  <button class="btn btn-secondary mt-2" (click)="loadClients()">
    Reintentar
  </button>
</div>

<div *ngIf="!loading && !error" class="data-table">
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nombre Completo</th>
        <th>Dirección</th>
        <th>Teléfono</th>
        <th>Estado</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let client of filteredClients; trackBy: trackByClientId">
        <td>{{ client.id }}</td>
        <td>{{ client.person.fullName }}</td>
        <td>{{ client.person.address }}</td>
        <td>{{ client.person.phone }}</td>
        <td>
          <span class="status-badge" [ngClass]="getStatusClass(client.status)">
            {{ getStatusText(client.status) }}
          </span>
        </td>
        <td>
          <div class="d-flex gap-1">
            <button 
              class="btn btn-warning btn-sm" 
              (click)="editClient(client.id!)"
              title="Editar">
              Editar
            </button>
            <button 
              *ngIf="!client.status"
              class="btn btn-success btn-sm" 
              (click)="activateClient(client.id!)"
              title="Activar">
              Activar
            </button>
            <button 
              *ngIf="client.status"
              class="btn btn-secondary btn-sm" 
              (click)="deactivateClient(client.id!)"
              title="Desactivar">
              Desactivar
            </button>
            <button 
              class="btn btn-danger btn-sm" 
              (click)="deleteClient(client.id!)"
              title="Eliminar">
              Eliminar
            </button>
          </div>
        </td>
      </tr>
      <tr *ngIf="filteredClients.length === 0">
        <td colspan="6" class="text-center">
          <em>No se encontraron clientes</em>
        </td>
      </tr>
    </tbody>
  </table>
</div>
